init:
    
    # Declare images below this line, using the image statement.
    image bg_lunch_day = "bg/Lunchroom_Day.jpg"
    image bg_lunch_night = "bg/Lunchroom_Night.jpg"
    image bg_train_station = "bg/Janet Lim Napoles International Airport.jpg"
    image bg_school_outdoors = "bg/practice_render_plus_post_process.jpg"
    image bg_classroom = "bg/Classroom_02_day.jpg"
    image bg_passenger_car = "bg/temp_passenger_car_bg.jpg"
    image ch_wyatt_neutral = im.Scale("characters/wyatt/Wyatt_pose1_neutral.png", 720, 1100)
    image ch_wyatt_happy = im.Scale("characters/wyatt/Wyatt_pose1_happy.png", 720, 1100)
    image ch_wyatt_blush = im.Scale("characters/wyatt/Wyatt_pose1_blush.png", 720, 1100)
    image ch_wyatt_anger = im.Scale("characters/wyatt/Wyatt_pose1_anger.png", 720, 1100)
    image ch_wyatt_confusion = im.Scale("characters/wyatt/Wyatt_pose1_confusion.png", 720, 1100)
    image ch_wyatt_irritated = im.Scale("characters/wyatt/Wyatt_pose1_irritated.png", 720, 1100)
    image ch_wyatt_nervous = im.Scale("characters/wyatt/Wyatt_pose1_nervous.png", 720, 1100)
    image ch_wyatt_stressed = im.Scale("characters/wyatt/Wyatt_pose1_stressed.png", 720, 1100)
    image ch_wyatt_laugh = im.Scale("characters/wyatt/Wyatt_pose1_laugh.png", 720, 1100)
    image ch_wyatt_scared = im.Scale("characters/wyatt/Wyatt_pose1_scared.png", 720, 1100)
    image ch_jodie_neutral = im.Scale("characters/jodie/jodie_pose1_neutral.png", 720, 1100)
    image ch_jodie_anger = im.Scale("characters/jodie/jodie_pose1_anger.png", 720, 1100)
    image ch_jodie_angerblush = im.Scale("characters/jodie/jodie_pose1_angerblush.png", 720, 1100)
    image ch_jodie_happy = im.Scale("characters/jodie/jodie_pose1_happy.png", 720, 1100)
    image ch_jodie_happyblush = im.Scale("characters/jodie/jodie_pose1_happyblush.png", 720, 1100)
    image ch_jodie_irritated = im.Scale("characters/jodie/jodie_pose1_irritated.png", 720, 1100)
    image ch_jodie_laugh = im.Scale("characters/jodie/jodie_pose1_laugh.png", 720, 1100)
    image ch_jodie_sad = im.Scale("characters/jodie/jodie_pose1_sad.png", 720, 1100)
    image ch_jodie_scared = im.Scale("characters/jodie/jodie_pose1_scared.png", 720, 1100)
    image ch_jodie_serious = im.Scale("characters/jodie/jodie_pose1_serious.png", 720, 1100)
    image ch_kaori_neutral = im.Scale("characters/kaori/Kaori_pose1_neutral.png", 720, 1100)
    image ch_kaori_happy = im.Scale("characters/kaori/Kaori_pose1_happyblush.png", 720, 1100)
    image ch_kaori_anger = im.Scale("characters/kaori/Kaori_pose1_anger.png", 720, 1100)
    image ch_kaori_irritated = im.Scale("characters/kaori/Kaori_pose1_irritated.png", 720, 1100)
    image ch_kaori_irritatedblush = im.Scale("characters/kaori/Kaori_pose1_irritatedblush.png", 720, 1100)
    image ch_kaori_laugh = im.Scale("characters/kaori/Kaori_pose1_laugh.png", 720, 1100)
    image ch_kaori_laughblush = im.Scale("characters/kaori/Kaori_pose1_laughblush.png", 720, 1100)
    image ch_kaori_sad = im.Scale("characters/kaori/Kaori_pose1_sad.png", 720, 1100)
    image ch_kaori_scared = im.Scale("characters/kaori/Kaori_pose1_scared.png", 720, 1100)
    image ch_kaori_serious = im.Scale("characters/kaori/Kaori_pose1_serious.png", 720, 1100)
    image ch_moriya_neutral = im.Scale("characters/moriya/moriya_pose1_neutral.png", 720, 1100)
    image ch_moriya_serious = im.Scale("characters/moriya/moriya_pose1_serious.png", 720, 1100)
    image ch_moriya_shocked = im.Scale("characters/moriya/moriya_pose1_shocked.png", 720, 1100)
    image ch_moriya_angry = im.Scale("characters/moriya/moriya_pose1_angry.png", 720, 1100)
    image ch_moriya_angrysmile = im.Scale("characters/moriya/moriya_pose1_angrysmile.png", 720, 1100)
    image ch_moriya_irritated = im.Scale("characters/moriya/moriya_pose1_irritated.png", 720, 1100)
    image ch_moriya_sad = im.Scale("characters/moriya/moriya_pose1_sad.png", 720, 1100)
    image ch_moriya_happyopeneyes = im.Scale("characters/moriya/moriya_pose1_happyopeneyes.png", 720, 1100)
    image ch_moriya_happyclosedeyes = im.Scale("characters/moriya/moriya_pose1_happyclosedeyes.png", 720, 1100)
    image ch_moriya_laugh = im.Scale("characters/moriya/moriya_pose1_laugh.png", 720, 1100)
    image ch_shimazu_neutral = im.Scale("characters/shimazu/shimazu_pose1_neutral.png", 720, 1100)
    image ch_shimazu_shocked = im.Scale("characters/shimazu/shimazu_pose1_shocked.png", 720, 1100)
    image ch_shimazu_laugh = im.Scale("characters/shimazu/shimazu_pose1_laugh.png", 720, 1100)
    image ch_shimazu_serious = im.Scale("characters/shimazu/shimazu_pose1_serious.png", 720, 1100)
    image ch_shimazu_serioussmile = im.Scale("characters/shimazu/shimazu_pose1_serioussmile.png", 720, 1100)
    image ch_shimazu_happy = im.Scale("characters/shimazu/shimazu_pose1_happy.png", 720, 1100)
    image ch_shimazu_blush = im.Scale("characters/shimazu/shimazu_pose1_blush.png", 720, 1100)
    image ch_shimazu_nervous = im.Scale("characters/shimazu/shimazu_pose1_nervous.png", 720, 1100)
    image ch_shimazu_irritated = im.Scale("characters/shimazu/shimazu_pose1_irritated.png", 720, 1100)
    image ch_shimazu_angry = im.Scale("characters/shimazu/shimazu_pose1_angry.png", 720, 1100)
    image ch_mitsuyo_neutral = im.Scale("characters/mitsuyo/mitsuyo_pose1_neutral.png", 720, 1100)
    image ch_mitsuyo_serious = im.Scale("characters/mitsuyo/mitsuyo_pose1_serious.png", 720, 1100)
    image ch_mitsuyo_seriousblush = im.Scale("characters/mitsuyo/mitsuyo_pose1_seriousblush.png", 720, 1100)
    image ch_mitsuyo_happy = im.Scale("charcters/mitsuyo/mitsuyo_pose1_happy.png", 720, 1100)
    image ch_mitsuyo_irritated = im.Scale("characters/mitsuyo/mitsuyo_pose1_irritated.png", 720, 1100)
    image ch_mitsuyo_irritatedclosedeyes = im.Scale("characters/mitsuyo/mitsuyo_pose1_irritatedclosedeyes.png", 720, 1100)
    image ch_mitsuyo_happyblush = im.Scale("characters/mitsuyo/mitsuyo_pose1_happyblush.png", 720, 1100)
    image ch_mitsuyo_angryeyes = im.Scale("characters/mitsuyo/mitsuyo_pose1_angryeyes.png", 720, 1100)
    image ch_mitsuyo_angry = im.Scale("characters/mitsuyo/mitsuyo_pose1_angry.png", 720, 1100)
    image ch_mitsuyo_sad = im.Scale("characters/mitsuyo/mitsuyo_pose1_sad.png", 720, 1100)
    image ch_anya_neutral = im.Scale("characters/anya/anya_pose1_neutral.png", 720, 1100)
    image ch_anya_shocked = im.Scale("characters/anya/anya_pose1_shocked.png", 720, 1100)
    image ch_anya_happyclosedeyes = im.Scale("characters/anya/anya_pose1_happyclosedeyes.png", 720, 1100)
    image ch_anya_nervous = im.Scale("characters/anya/anya_pose1_nervous.png", 720, 1100)
    image ch_anya_happy = im.Scale("characters/anya/anya_pose1_happy.png", 720, 1100)
    image ch_anya_serious = im.Scale("characters/anya/anya_pose1_serious.png", 720, 1100)
    image ch_anya_blush = im.Scale("characters/anya/anya_pose1_blush.png", 720, 1100)
    image ch_anya_angryclosedeyes = im.Scale("characters/anya/anya_pose1_angryclosedeyes.png", 720, 1100)
    image ch_anya_angry = im.Scale("characters/anya/anya_pose1_angry.png", 720, 1100)
    image ch_anya_sad = im.Scale("characters/anya/anya_pose1_sad.png", 720, 1100)
    image ch_evelyn_neutral = im.Scale("characters/evelyn/evelyn_pose1_neutral.png", 720, 1100)
    image ch_evelyn_serious = im.Scale("characters/evelyn/evelyn_pose1_serious.png", 720, 1100)
    image ch_evelyn_seriousopen = im.Scale("charcters/evelyn/evelyn_pose1_seriousopen.png", 720, 1100)
    image ch_evelyn_nervous = im.Scale("characters/evelyn/evelyn_pose1_nervous.png", 720, 1100)
    image ch_evelyn_shocked = im.Scale("characters/evelyn/evelyn_pose1_shocked.png", 720, 1100)
    image ch_evelyn_laugh = im.Scale("characters/evelyn/evelyn_pose1_laugh.png", 720, 1100)
    image ch_evelyn_sad = im.Scale("characters/evelyn/evelyn_pose1_sad.png", 720, 1100)
    image ch_evelyn_happy = im.Scale("characters/evelyn/evelyn_pose1_happy.png", 720, 1100)
    image ch_evelyn_happyeyesclosed = im.Scale("characters/evelyn/evelyn_pose1_happyeyesclosed.png", 720, 1100)
    image ch_evelyn_blush = im.Scale("characters/evelyn/evelyn_pose1_blush.png", 720, 1100)

    # codeBlc Character Defines
    # Declare characters used by this game.
    define w = Character('Wyatt', color="#c8ffc8")
    define tc = Character('Intercom', color="#c8ffc8")
    define qm = Character ('????', color="#c8ffc8")
    define j = Character ('Jodie', color="#c8ffc8")
    define d = Character ('SLA Device', color="#c8ffc8")
    define sh = Character ('Dr. Shimazu', color="#c8ffc8")
    define k = Character ('Kaori', color="#c8ffc8")
#    $ centered = Character(None, xalign=0.5, yalign=0.5)
    define narrate = Character(' ', color="#000000")
    define m = Character('Moriya', color="#c8ffc8")
    define n = Character('Niklas', color="#c8ffc8")
    define l = Character('Lukas', color="#c8ffc8")
    define a = Character('Anya', color="#c8ffc8")
    define js = Character('Jonas', color="#c8ffc8")
    define mi = Character('Mitsuyo', color="#c8ffc8")
    define wi = Character('William', color="#c8ffc8")
    define y = Character('Yvonne', color="#c8ffc8")
    define h = Character('Heidler', color="#c8ffc8")
    define ple = Character('Plebian', color="#c8ffc8")
    define ha = Character('Hackett', color="#c8ffc8")
    define ch = Character('Chris', color="#c8ffc8")
    define e = Character('Evelyn', color="#c8ffc8")
    define t = Character('Torsten', color="#c8ffc8")
    define car = Character('Cartwright', color="#c8ffc8")
    define al = Character('Alyssa', color="#c8ffc8")
    define mrcar = Character('Mr Cartwright', color="#c8ffc8")
    define mrscar = Character('Mrs Armstrong', color="#c8ffc8")
    define er = Character('Eric', color="#c8ffc8")
    define sl = Character('Squad Leader', color="#c8ffc8")
    define p = Character('Pointman', color="#c8ffc8")
    define pro = Character('Profressor', color="#c8ffc8")
    define ko = Character('Dr Koshiba', color="#c8ffc8")
    define hns = Character('Hans', color="#c8ffc8")
    define alx = Character('Alexander', color="#c8ffc8")
    define lh = Character('Laurence', color="#c8ffc8")
    define g = Character('Guard', color="#c8ffc8")
    define jo = Character('Joshua', color="#c8ffc8")
    define he = Character('Heidler', color="#c8ffc8") 
    # endBlc
